#!/bin/bash


### This script probes 'src' and populates 'bak' and 'bin'.


# get the name of the directory this script lives in.
# We want to process things relative to where this script lives,
# not relative to where it is being executed.
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SRC_DIR="$DIR/src"
BIN_DIR="$DIR/bin"
BAK_DIR="$DIR/bak"

mkdir -p "$BIN_DIR"

(cd "$DIR"
cat >index.html <<EOF
<!DOCTYPE html>
<html>
<head>
<title>A spicy blog</title>
</head>
<body>
<h1>My Blog!</h1>
EOF
)

for s in `ls $SRC_DIR`; do (cd "$SRC_DIR"

  source "$s"

  # add an entry in index.html
  (cd "$DIR"
    echo "<a href=\"blog/bin/$s.html\">$TITLE</a>" >> index.html
  )

  # do nothing else if nothing has changed.
  if [ -d "$BAK_DIR/$s" ] && [ "$(ls "$BAK_DIR/$s")" ]; then
    LATEST=$(ls "$BAK_DIR/$s" | sort -n | tail -n 1)
    echo "$LATEST"
    if diff "$BAK_DIR/$s/$LATEST" "$s" 2>&1 1>/dev/null; then
      continue
    fi
  fi

  # create a backup
  mkdir -p "$BAK_DIR/$s"
  cp "$s" "$BAK_DIR/$s/$(date +%s)"

  # finally write the html
  DST_FILE="$BIN_DIR/$s.html"
  BODY=`echo "$BODY" | pandoc -f markdown -t html`
  cat >"$BIN_DIR/$s.html" <<EOF
<!DOCTYPE html>
<html>
<head>
<title>$TITLE</title>
</head>
<body>
<div>
$BODY
</div>
<div>
<p>Created $(date -r"$(ls "$BAK_DIR/$s" | sort -n | head -n 1)")</p>
<p>Last Modified $(date -r"$(ls "$BAK_DIR/$s" | sort -n | tail -n 1)")</p>
</div>
</body>
</html>
EOF
); done


(cd "$DIR"
cat >>index.html <<EOF
</body>
</html>
EOF
)
